"""initial

Revision ID: 99729d64fbc6
Revises: 
Create Date: 2025-11-08 16:25:38.435603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tgbot


# revision identifiers, used by Alembic.
revision: str = '99729d64fbc6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.Column('button_index', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_active_choice', 'choices', ['distribution_id', 'button_index'], unique=True, postgresql_where=sa.text('active = true'))
    op.create_table('distributions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('range_data', tgbot.db.models.distribution.DistributionRangeType(), nullable=False),
    sa.Column('count_choices', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('distributions')
    op.drop_index('uq_active_choice', table_name='choices', postgresql_where=sa.text('active = true'))
    op.drop_table('choices')
    op.drop_table('users')
    # ### end Alembic commands ###
