"""added uuid for DBDistribution

Revision ID: e9edff7369c5
Revises: 99729d64fbc6
Create Date: 2026-02-15 00:26:00.477047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9edff7369c5'
down_revision: Union[str, Sequence[str], None] = '99729d64fbc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distributions', sa.Column('uuid', sa.UUID(), nullable=False, server_default=sa.text("gen_random_uuid()")))
    op.create_unique_constraint(None, 'distributions', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'distributions', type_='unique')
    op.drop_column('distributions', 'uuid')
    # ### end Alembic commands ###
